### PR TITLE
add support to csv format

### PR DESCRIPTION
**Pull request by rittme**
This PR adds support to formatting the output as CSV data.

### CODE REVIEW

**Comment by rittme** [comment]
Sorry for the delay. I hope this looks better :)

**Comment by rittme** [comment]
Hey @masawada, do you need me to change anything else on this?

**Comment by masawada** [comment]
Sorry, I missed the notification! Thanks for your contribution!

**Review by masawada — APPROVED** [review]

**Comment by masawada** [comment]
@rittme I released the changes as v2.2.0. Thank you so much!  
https://www.npmjs.com/package/yarn-outdated-formatter/v/2.2.0

**Comment by rittme** [comment]
Thank you @masawada. You package is quite helpful, it was nice to be able to contribute :)

**Pull request merged**
