### PR TITLE
Change behaviour of pre-release version numbers to match that of yarn

### PR DESCRIPTION
**Pull request by jamesastubbs**
The output from the `yarn outdated` command colourises the package names, denoting whether the change in between versions is a `major`, `minor` or `patch`, e.g.:

Screenshot 2021-01-05 at 12 13 37

In this example, the package `sharp` is identified as a major version change from `0.25.4` to `0.27.0` as the major version number is set to `0`.

The [semver utility](https://github.com/yarnpkg/yarn/blob/master/src/util/semver.js) used by the `yarn outdated` command has logic to determine major/minor/patch changes differently if the major and/or minor number is set to `0`, as can be found here: https://github.com/yarnpkg/yarn/blob/master/src/util/semver.js (commit hash is `3119382885ea373d3c13d6a846de743eca8c914b` at the time of writing this PR).

This PR simply copies this behaviour from the yarn `semver.js` utility and applies it to this yarn output formatter. The output generated from this formatter now handles pre-major and pre-minor version numbers in the same way that yarn does.

### CODE REVIEW

**Review by masawada — APPROVED** [review]
@jamesastubbs Thank you for your great contribution! 
I am planning to include this change in v3.0.0 since I think it is a breaking change.

**Comment by jamesastubbs** [comment]
👍 No problem. Marking this as a breaking change seems to make sense.
Any ideas when you're looking to release `v3.0.0`?

**Comment by masawada** [comment]
@jamesastubbs Sorry for my late response! I will publish it from now.

**Comment by masawada** [comment]
@jamesastubbs I released v3.0.0. Thank you so much!
https://www.npmjs.com/package/yarn-outdated-formatter/v/3.0.0

**Pull request merged**
